using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using Microsoft.Extensions.Logging;

namespace Soenneker.Quark.Gen.Tailwind.BuildTasks;

internal static class QuarkThemeTailwindCssResolver
{
    private const string _manifestTypeName = "Soenneker.Quark.Gen.Themes.Generated.QuarkThemeCssManifest";
    private const string _manifestFieldName = "Data";
    private const string _themeTailwindCssGeneratorTypeName = "Soenneker.Quark.ThemeTailwindCssGenerator";

    public static string? TryGenerate(string? targetPath, ILogger logger)
    {
        if (string.IsNullOrWhiteSpace(targetPath))
            return null;

        targetPath = SanitizePathArg(targetPath);

        if (string.IsNullOrWhiteSpace(targetPath) || !File.Exists(targetPath))
            return null;

        string fullTargetPath = Path.GetFullPath(targetPath);
        string targetDir = Path.GetDirectoryName(fullTargetPath) ?? Directory.GetCurrentDirectory();

        try
        {
            var loadContext = new ProbingLoadContext(targetDir);
            Assembly asm = loadContext.LoadFromAssemblyPath(fullTargetPath);

            LoadReferencedAssemblies(loadContext, asm.GetReferencedAssemblies());

            string? manifest = ReadManifest(asm);
            if (string.IsNullOrWhiteSpace(manifest))
                return null;

            Type? generatorType = FindLoadedType(loadContext, _themeTailwindCssGeneratorTypeName);
            if (generatorType is null)
            {
                logger.LogInformation("Quark theme manifest was found, but {GeneratorType} could not be loaded.", _themeTailwindCssGeneratorTypeName);
                return null;
            }

            List<ManifestEntry> entries = ParseManifest(manifest).ToList();
            if (entries.Count == 0)
                return null;

            if (entries.Count > 1)
            {
                logger.LogWarning(
                    "Multiple Quark theme CSS manifest entries were found. Tailwind theme token CSS will use {ThemeTypeName}.",
                    entries[0].ThemeTypeName);
            }

            ManifestEntry entry = entries[0];
            Type? themeType = asm.GetType(entry.ThemeTypeName, throwOnError: false, ignoreCase: false);
            if (themeType is null)
            {
                logger.LogWarning("Skipping Quark theme token CSS because type {ThemeTypeName} could not be found.", entry.ThemeTypeName);
                return null;
            }

            MemberInfo? factory = FindSingleThemeFactory(themeType);
            if (factory is null)
            {
                logger.LogWarning("Skipping Quark theme token CSS for {ThemeTypeName} because no unique theme factory was found.", entry.ThemeTypeName);
                return null;
            }

            object? themeInstance = factory switch
            {
                PropertyInfo p => p.GetValue(null),
                MethodInfo m => InvokeThemeFactory(m),
                _ => null
            };

            if (themeInstance is null)
            {
                logger.LogWarning("Skipping Quark theme token CSS for {ThemeTypeName} because the factory returned null.", entry.ThemeTypeName);
                return null;
            }

            MethodInfo? generateMethod = FindSingleArgMethod(generatorType, "Generate", themeInstance.GetType());
            if (generateMethod is null)
            {
                logger.LogInformation("Quark theme token CSS generator did not expose a compatible Generate method.");
                return null;
            }

            string? css = generateMethod.Invoke(null, [themeInstance]) as string;
            if (string.IsNullOrWhiteSpace(css))
                return null;

            return "/* Auto-generated by Soenneker.Quark.Gen.Tailwind from Quark Theme tokens. */" + Environment.NewLine +
                   Environment.NewLine +
                   css.TrimEnd();
        }
        catch (Exception ex)
        {
            logger.LogInformation(ex, "Unable to resolve Quark theme token CSS from {TargetPath}. Falling back to shadcn theme config.", fullTargetPath);
            return null;
        }
    }

    private static string SanitizePathArg(string value)
    {
        value = value.Trim();
        int quoteIdx = value.IndexOf('"');
        if (quoteIdx >= 0)
            value = value[..quoteIdx];

        return value.Trim().Trim('"', '\\', ' ');
    }

    private static void LoadReferencedAssemblies(AssemblyLoadContext context, IEnumerable<AssemblyName> refs)
    {
        foreach (AssemblyName refName in refs)
        {
            try
            {
                context.LoadFromAssemblyName(refName);
            }
            catch
            {
                // Optional references are allowed to fail here; direct type lookup below decides whether theme generation can continue.
            }
        }
    }

    private static string? ReadManifest(Assembly asm)
    {
        Type? type = asm.GetType(_manifestTypeName, throwOnError: false, ignoreCase: false);
        if (type is null)
            return null;

        FieldInfo? field = type.GetField(_manifestFieldName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
        return field?.FieldType == typeof(string) ? field.GetRawConstantValue() as string : null;
    }

    private static Type? FindLoadedType(AssemblyLoadContext context, string fullName)
    {
        foreach (Assembly assembly in context.Assemblies)
        {
            try
            {
                Type? type = assembly.GetType(fullName, throwOnError: false, ignoreCase: false);
                if (type is not null)
                    return type;
            }
            catch
            {
                // Keep probing other assemblies.
            }
        }

        return null;
    }

    private static MemberInfo? FindSingleThemeFactory(Type themeClass)
    {
        MemberInfo? match = null;

        foreach (PropertyInfo prop in themeClass.GetProperties(BindingFlags.Public | BindingFlags.Static))
        {
            if (prop.GetMethod is null || !IsThemeType(prop.PropertyType))
                continue;

            if (match is not null)
                return null;

            match = prop;
        }

        foreach (MethodInfo method in themeClass.GetMethods(BindingFlags.Public | BindingFlags.Static))
        {
            if (!IsThemeFactoryMethod(method) || !IsThemeType(method.ReturnType))
                continue;

            if (match is not null)
                return null;

            match = method;
        }

        return match;
    }

    private static bool IsThemeType(Type type) => string.Equals(type.FullName, "Soenneker.Quark.Theme", StringComparison.Ordinal);

    private static bool IsThemeFactoryMethod(MethodInfo method)
    {
        ParameterInfo[] parameters = method.GetParameters();
        if (parameters.Length == 0)
            return true;

        return parameters.Length == 1 && typeof(IServiceProvider).IsAssignableFrom(parameters[0].ParameterType);
    }

    private static object? InvokeThemeFactory(MethodInfo method)
    {
        ParameterInfo[] parameters = method.GetParameters();
        if (parameters.Length == 0)
            return method.Invoke(null, null);

        return method.Invoke(null, [EmptyServiceProvider.Instance]);
    }

    private static MethodInfo? FindSingleArgMethod(Type type, string name, Type argType)
    {
        foreach (MethodInfo method in type.GetMethods(BindingFlags.Public | BindingFlags.Static))
        {
            if (!string.Equals(method.Name, name, StringComparison.Ordinal))
                continue;

            ParameterInfo[] parameters = method.GetParameters();
            if (parameters.Length != 1)
                continue;

            if (parameters[0].ParameterType.IsAssignableFrom(argType))
                return method;
        }

        return null;
    }

    private static IEnumerable<ManifestEntry> ParseManifest(string data)
    {
        string[] lines = data.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);

        foreach (string line in lines)
        {
            int firstSep = line.IndexOf('|');
            if (firstSep <= 0 || firstSep >= line.Length - 1)
                continue;

            string typeName = line[..firstSep].Trim();
            if (typeName.Length == 0)
                continue;

            yield return new ManifestEntry(typeName);
        }
    }

    private sealed record ManifestEntry(string ThemeTypeName);

    private sealed class EmptyServiceProvider : IServiceProvider
    {
        public static readonly EmptyServiceProvider Instance = new();

        public object? GetService(Type serviceType) => null;
    }
}
